### ISSUE TITLE
Scheduled jobs shouldn't be allowed to run on forks

### ISSUE THREAD

**Issue by maximlt** [pyviz-dev/holoviz_tasks#7]
For some reason GitHub allows scheduled jobs to run on forks and there's no easy way to deactivate that https://github.com/community/community/discussions/16109.

Currently the way to do that is to add a condition on the job https://github.com/orgs/community/discussions/26684#discussioncomment-3252843

```
Jobs:
  build:
    if: (github.event_name == 'schedule' && github.repository == 'main_org/main_repo') || (github.event_name != 'schedule')
    . . .
```

- [ ] Panel
- [ ] hvPlot
- [ ] HoloViews
- [ ] GeoViews
- [ ] Datashader
- [ ] Lumen
- [ ] Param
- [ ] Colorcet
- [ ] HoloViz.org
- [ ] Pyviz.org
- [ ] examples.pyviz.org
